print('Hello World!')
print('I love Python programming')
print('Do you guys enjoy the lesson?')
print('Python is the best programming language')
print('======== we can print any thing ======')
print('Asabeneh', 'Yetayeh', 'Finland', 'Helsinki', 250)
print("We can use a single or a double quote to write a string in Python")
print('The symobol # is used to do commenting in Python')